-- Script: assignment_rowtype_anchoring_with_percent_rowtype.sql
-- Session: 030 - Row Type Anchoring with %ROWTYPE (Production Patterns)
-- Format:
--   • 10 detailed questions with complete solutions provided as COMMENTED hints.
--   • To run a solution: copy the commented block and remove leading '--'.
-- Guidance:
--   • Use table%ROWTYPE when working with many columns from a single table row.
--   • Use cursor%ROWTYPE for projections that don't match a base table.
--   • With RETURNING INTO, list individual record fields explicitly (r.col1, r.col2, ...).

SET SERVEROUTPUT ON;

--------------------------------------------------------------------------------
-- Q1 (Basic fetch): Declare r emp_row_demo%ROWTYPE; select row for emp_id=1; print name and salary.
-- Answer (commented):
-- DECLARE
--   r emp_row_demo%ROWTYPE;
-- BEGIN
--   SELECT * INTO r FROM emp_row_demo WHERE emp_id=1;
--   DBMS_OUTPUT.PUT_LINE('name='||r.emp_name||', salary='||r.salary);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q2 (Field update): Load id=2 into r; add 500 to salary in record; push to table; show SQL%%ROWCOUNT.
-- Answer (commented):
-- DECLARE
--   r emp_row_demo%ROWTYPE;
-- BEGIN
--   SELECT * INTO r FROM emp_row_demo WHERE emp_id=2;
--   r.salary := NVL(r.salary,0) + 500;
--   UPDATE emp_row_demo SET salary=r.salary WHERE emp_id=r.emp_id;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q3 (INSERT via record): Build r then insert new row id=5; RETURNING INTO r.emp_id, r.emp_name.
-- Answer (commented):
-- DECLARE
--   r emp_row_demo%ROWTYPE;
-- BEGIN
--   r.emp_id := 5; r.emp_name := 'Kavya'; r.dept_id := 20; r.salary := 68000; r.email := 'kavya@example.com'; r.hired_on := SYSDATE;
--   INSERT INTO emp_row_demo(emp_id,emp_name,dept_id,salary,email,hired_on)
--   VALUES(r.emp_id,r.emp_name,r.dept_id,r.salary,r.email,r.hired_on)
--   RETURNING emp_id, emp_name INTO r.emp_id, r.emp_name;
--   DBMS_OUTPUT.PUT_LINE('inserted id='||r.emp_id||' name='||r.emp_name);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q4 (UPDATE RETURNING): Update id=3 email and raise salary; RETURNING INTO record fields; print.
-- Answer (commented):
-- DECLARE
--   r emp_row_demo%ROWTYPE;
-- BEGIN
--   UPDATE emp_row_demo
--   SET    email='mani.rev@example.com', salary=salary+400
--   WHERE  emp_id=3
--   RETURNING emp_id, emp_name, dept_id, salary, email, hired_on
--   INTO      r.emp_id, r.emp_name, r.dept_id, r.salary, r.email, r.hired_on;
--   DBMS_OUTPUT.PUT_LINE('id='||r.emp_id||' new_sal='||r.salary||' mail='||r.email);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q5 (cursor%ROWTYPE join): Declare cursor selecting emp_name, dept_name; FETCH into r and print.
-- Answer (commented):
-- DECLARE
--   CURSOR c IS
--     SELECT e.emp_name, d.dept_name
--     FROM emp_row_demo e JOIN dept_row_demo d ON d.dept_id=e.dept_id
--     ORDER BY e.emp_id;
--   r c%ROWTYPE;
-- BEGIN
--   OPEN c;
--   LOOP
--     FETCH c INTO r; EXIT WHEN c%NOTFOUND;
--     DBMS_OUTPUT.PUT_LINE(r.emp_name||' - '||r.dept_name);
--   END LOOP;
--   CLOSE c;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q6 (Cursor FOR LOOP): Print 'id=..., name=...' using implicit record over all employees.
-- Answer (commented):
-- BEGIN
--   FOR rec IN (SELECT emp_id, emp_name FROM emp_row_demo ORDER BY emp_id) LOOP
--     DBMS_OUTPUT.PUT_LINE('id='||rec.emp_id||', name='||rec.emp_name);
--   END LOOP;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q7 (Function returns %ROWTYPE): Write get_emp(p_id) RETURN emp_row_demo%%ROWTYPE and print emp_name.
-- Answer (commented):
-- DECLARE
--   FUNCTION get_emp(p_id IN emp_row_demo.emp_id%TYPE) RETURN emp_row_demo%ROWTYPE IS
--     r emp_row_demo%ROWTYPE;
--   BEGIN
--     SELECT * INTO r FROM emp_row_demo WHERE emp_id=p_id; RETURN r;
--   END;
-- BEGIN
--   DBMS_OUTPUT.PUT_LINE(get_emp(1).emp_name);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q8 (Defensive init): Load id=2 into r; set r.email to COALESCE(r.email, r.emp_name||'@example.com'); update.
-- Answer (commented):
-- DECLARE
--   r emp_row_demo%ROWTYPE;
-- BEGIN
--   SELECT * INTO r FROM emp_row_demo WHERE emp_id=2;
--   r.email := COALESCE(r.email, r.emp_name||'@example.com');
--   UPDATE emp_row_demo SET email=r.email WHERE emp_id=r.emp_id;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q9 (Mix with %TYPE): Declare v_dept dept_row_demo.dept_name%%TYPE; load r for id=1; print name + dept via SELECT.
-- Answer (commented):
-- DECLARE
--   r emp_row_demo%ROWTYPE;
--   v_dept dept_row_demo.dept_name%TYPE;
-- BEGIN
--   SELECT * INTO r FROM emp_row_demo WHERE emp_id=1;
--   SELECT dept_name INTO v_dept FROM dept_row_demo WHERE dept_id=r.dept_id;
--   DBMS_OUTPUT.PUT_LINE(r.emp_name||' ('||v_dept||')');
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q10 (Parameterized cursor with cursor%ROWTYPE): c_emp(p_dept) returning emp_id,emp_name; loop & print.
-- Answer (commented):
-- DECLARE
--   CURSOR c_emp(p_dept NUMBER) IS
--     SELECT emp_id, emp_name FROM emp_row_demo WHERE dept_id=p_dept ORDER BY emp_id;
--   r c_emp%ROWTYPE;
-- BEGIN
--   OPEN c_emp(10);
--   LOOP
--     FETCH c_emp INTO r; EXIT WHEN c_emp%NOTFOUND;
--     DBMS_OUTPUT.PUT_LINE('id='||r.emp_id||' name='||r.emp_name);
--   END LOOP;
--   CLOSE c_emp;
-- END;
-- /
--------------------------------------------------------------------------------
-- End of Assignment
--------------------------------------------------------------------------------
