-- Demo Script: learning_log_demo.sql
-- Objective: Build a self-tracking system for PL/SQL learning

CONNECT plsql_lab/oracle123@localhost:1521/xepdb1;

CREATE TABLE learning_log (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  topic VARCHAR2(100),
  practice_done CHAR(1),
  reflection_date DATE DEFAULT SYSDATE
);

INSERT INTO learning_log (topic, practice_done)
VALUES ('Accelerated Learning Setup', 'Y');

SELECT * FROM learning_log;
