-- Demo Script: sql_developer_connection_setup.sql
-- Objective: Validate Oracle SQL Developer connection

CONNECT plsql_lab/oracle123@localhost:1521/xepdb1;

-- Check session information
SELECT user, sysdate AS connection_verified FROM dual;

-- Display current schema objects
SELECT object_name, object_type FROM user_objects;

-- Test query execution
CREATE TABLE tool_config_test (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  description VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO tool_config_test (description) VALUES ('SQL Developer Connection Validated');
COMMIT;

SELECT * FROM tool_config_test;
