-- Script: assignment_practical_workshop_3_combined_crud_patterns.sql
-- Session: 034 - Practical Workshop #3 (Combined CRUD Patterns)
-- Format:
--   • 10 detailed questions with complete solutions provided as COMMENTED hints.
--   • To run a solution: copy the commented block and remove leading '--'.
-- Guidance:
--   • Validate first with dry-run queries; use RETURNING INTO to avoid re-selects.
--   • Favor MERGE for set-based upserts; audit SQL%%ROWCOUNT after DML.
--   • Save partial work with SAVEPOINT; rollback failing step only.

SET SERVEROUTPUT ON;

--------------------------------------------------------------------------------
-- Q1 (INSERT + RETURNING): Create a new order for cust_id=2 with one line for SKU-3 (qty=1).
-- Answer (commented):
-- DECLARE
--   v_order_id orders_hdr.order_id%TYPE := 1002;
-- BEGIN
--   INSERT INTO orders_hdr(order_id,cust_id,order_status,grand_total) VALUES (v_order_id,2,'NEW',0);
--   INSERT INTO orders_line(line_id, order_id, sku, qty, price_each, line_total)
--   SELECT 10021, v_order_id, 'SKU-3', 1, p.price, p.price FROM products p WHERE p.sku='SKU-3';
--   UPDATE orders_hdr h SET h.grand_total=(SELECT SUM(line_total) FROM orders_line WHERE order_id=v_order_id)
--   WHERE h.order_id=v_order_id;
--   DBMS_OUTPUT.PUT_LINE('created order '||v_order_id);
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q2 (SELECT validation): Ensure order_id=1002 has at least one line and total>0.
-- Answer (commented):
-- DECLARE
--   v_ok NUMBER;
-- BEGIN
--   SELECT COUNT(*) INTO v_ok FROM orders_line WHERE order_id=1002;
--   IF v_ok=0 THEN DBMS_OUTPUT.PUT_LINE('No lines!'); ELSE DBMS_OUTPUT.PUT_LINE('OK lines='||v_ok); END IF;
--   IF EXISTS(SELECT 1 FROM orders_hdr WHERE order_id=1002 AND grand_total>0) THEN DBMS_OUTPUT.PUT_LINE('Total OK'); END IF;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q3 (UPDATE with version): Add 75 with version check and audit.
-- Answer (commented):
-- DECLARE
--   v_ver NUMBER;
-- BEGIN
--   SELECT version_no INTO v_ver FROM orders_hdr WHERE order_id=1002 FOR UPDATE;
--   UPDATE orders_hdr SET grand_total=grand_total+75, version_no=version_no+1, last_updated=SYSDATE
--   WHERE order_id=1002 AND version_no=v_ver;
--   INSERT INTO audit_log(entity,entity_id,action,details) VALUES ('ORDER','1002','ADJUST','+75 with version '||v_ver);
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q4 (MERGE upsert): Upsert product SKU-5 with price 450; update if exists.
-- Answer (commented):
-- BEGIN
--   MERGE INTO products t
--   USING (SELECT 'SKU-5' sku, 450 price FROM dual) s
--   ON (t.sku=s.sku)
--   WHEN MATCHED THEN UPDATE SET t.price=s.price, t.version_no=t.version_no+1, t.last_updated=SYSDATE
--   WHEN NOT MATCHED THEN INSERT (sku,name,price,active,version_no,last_updated)
--        VALUES (s.sku,'Gadget',s.price,'Y',1,SYSDATE);
--   DBMS_OUTPUT.PUT_LINE('merge rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q5 (Archive before delete): Archive orders older than 90 days then delete.
-- Answer (commented):
-- DECLARE
--   v_a NUMBER; v_d NUMBER;
-- BEGIN
--   INSERT INTO orders_archive SELECT * FROM orders_hdr WHERE created_on < SYSDATE-90;
--   v_a := SQL%ROWCOUNT;
--   DELETE FROM orders_hdr WHERE created_on < SYSDATE-90;
--   v_d := SQL%ROWCOUNT;
--   DBMS_OUTPUT.PUT_LINE('archived='||v_a||' deleted='||v_d);
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q6 (Soft delete + purge): Mark order_id=1002 as deleted then purge if older than 30 days.
-- Answer (commented):
-- BEGIN
--   UPDATE orders_hdr SET is_deleted='Y', deleted_on=SYSDATE WHERE order_id=1002;
--   UPDATE orders_hdr SET deleted_on=SYSDATE-31 WHERE order_id=1002;
--   DELETE FROM orders_hdr WHERE is_deleted='Y' AND deleted_on < SYSDATE-30;
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q7 (SAVEPOINT choreography): Apply two steps; rollback second on failure but keep first.
-- Answer (commented):
-- BEGIN
--   SAVEPOINT s1;
--   UPDATE orders_hdr SET order_status='APPROVED' WHERE order_id=1002;
--   SAVEPOINT s2;
--   UPDATE orders_hdr SET grand_total=grand_total + 99999 WHERE order_id=-1; -- none
--   IF SQL%ROWCOUNT=0 THEN ROLLBACK TO s2; END IF;
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q8 (Bulk FORALL): Increase price_each by 2% for lines (10011,10012,00000) capturing exceptions.
-- Answer (commented):
-- DECLARE
--   TYPE t_ids IS TABLE OF orders_line.line_id%TYPE;
--   ids t_ids := t_ids(10011,10012,0);
--   errors EXCEPTION; PRAGMA EXCEPTION_INIT(errors,-24381);
-- BEGIN
--   BEGIN
--     FORALL i IN 1..ids.COUNT SAVE EXCEPTIONS
--       UPDATE orders_line SET price_each=ROUND(price_each*1.02,2), line_total=ROUND(qty*ROUND(price_each*1.02,2),2)
--       WHERE line_id=ids(i);
--   EXCEPTION WHEN errors THEN DBMS_OUTPUT.PUT_LINE('bulk errors='||SQL%BULK_EXCEPTIONS.COUNT);
--   END;
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q9 (Dry-run verification): Print how many orders would be purged for soft-deleted > 60 days.
-- Answer (commented):
-- DECLARE
--   v NUMBER;
-- BEGIN
--   SELECT COUNT(*) INTO v FROM orders_hdr WHERE is_deleted='Y' AND deleted_on < SYSDATE-60;
--   DBMS_OUTPUT.PUT_LINE('would purge='||v);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q10 (Recovery test): Restore one archived order back to live table.
-- Answer (commented):
-- DECLARE
--   v NUMBER;
-- BEGIN
--   SELECT COUNT(*) INTO v FROM orders_archive;
--   IF v>0 THEN
--     INSERT INTO orders_hdr SELECT * FROM orders_archive WHERE ROWNUM=1;
--     DBMS_OUTPUT.PUT_LINE('restored 1 row');
--   ELSE
--     DBMS_OUTPUT.PUT_LINE('no archive rows');
--   END IF;
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------
-- End of Assignment
--------------------------------------------------------------------------------
