-- Script: assignment_return_statement_mechanics.sql
-- Session: 043 - RETURN Statement Mechanics
SET SERVEROUTPUT ON;

-- Q1 Single return
-- CREATE OR REPLACE FUNCTION f1(x IN NUMBER) RETURN NUMBER IS v NUMBER; BEGIN v := NVL(x,0) * 2; RETURN v; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f1(10)='||f1(10)); END; /

-- Q2 Guard clause
-- CREATE OR REPLACE FUNCTION f2(n IN NUMBER) RETURN NUMBER IS BEGIN IF n IS NULL OR n <= 0 THEN RETURN 0; END IF; RETURN n*n; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f2(-2)='||f2(-2)); END; /

-- Q3 %TYPE return
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE t PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
-- CREATE TABLE t(a NUMBER); /
-- CREATE OR REPLACE FUNCTION f3 RETURN t.a%TYPE IS BEGIN RETURN 42; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f3()='||f3); END; /

-- Q4 Exception->value
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE tt PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
-- CREATE TABLE tt(id NUMBER PRIMARY KEY, val NUMBER); /
-- INSERT INTO tt VALUES(1,99); COMMIT; /
-- CREATE OR REPLACE FUNCTION f4(p_id IN NUMBER, p_def IN NUMBER := 0) RETURN NUMBER IS v NUMBER; BEGIN SELECT val INTO v FROM tt WHERE id=p_id; RETURN v; EXCEPTION WHEN NO_DATA_FOUND THEN RETURN p_def; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f4(1)='||f4(1)); DBMS_OUTPUT.PUT_LINE('f4(9)='||f4(9)); END; /

-- Q5 Compose result
-- CREATE OR REPLACE FUNCTION f5(base IN NUMBER, rate IN NUMBER := 0.1, disc IN NUMBER := 0) RETURN NUMBER IS v_tax NUMBER := ROUND(NVL(base,0)*NVL(rate,0),2); v_disc NUMBER := ROUND(NVL(base,0)*NVL(disc,0)/100,2); BEGIN RETURN ROUND(NVL(base,0)+v_tax-v_disc,2); END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f5='||f5(1000,0.18,5)); END; /

-- Q6 Nested block return
-- CREATE OR REPLACE FUNCTION f6(flag IN BOOLEAN) RETURN VARCHAR2 IS v VARCHAR2(20) := 'start'; BEGIN DECLARE inner VARCHAR2(20) := 'inner'; BEGIN IF flag THEN RETURN 'early'; END IF; v := inner; END; RETURN v; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f6(TRUE)='||f6(TRUE)); DBMS_OUTPUT.PUT_LINE('f6(FALSE)='||f6(FALSE)); END; /

-- Q7 All paths return
-- CREATE OR REPLACE FUNCTION f7(n IN NUMBER) RETURN VARCHAR2 IS BEGIN IF n < 0 THEN RETURN 'NEG'; ELSIF n = 0 THEN RETURN 'ZERO'; ELSE RETURN 'POS'; END IF; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f7(-1)='||f7(-1)); END; /

-- Q8 NULL-safe
-- CREATE OR REPLACE FUNCTION f8(n IN NUMBER) RETURN NUMBER IS v NUMBER; BEGIN v := NVL(n,-1); RETURN v; END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f8(NULL)='||f8(NULL)); END; /

-- Q9 Procedure clarification
-- CREATE OR REPLACE PROCEDURE p9(quit IN BOOLEAN) IS BEGIN IF quit THEN RETURN; END IF; DBMS_OUTPUT.PUT_LINE('did work'); END; /
-- BEGIN p9(TRUE); p9(FALSE); END; /

-- Q10 Validate then compute
-- CREATE OR REPLACE FUNCTION f10(x IN NUMBER) RETURN NUMBER IS BEGIN IF x IS NULL OR x < 0 THEN RETURN -1; END IF; RETURN ROUND(SQRT(x), 4); END; /
-- BEGIN DBMS_OUTPUT.PUT_LINE('f10(9)='||f10(9)); DBMS_OUTPUT.PUT_LINE('f10(-1)='||f10(-1)); END; /
