-- Script: assignment_embedded_query_statements.sql
-- Session: 028 - Embedded Query Statements (Production Patterns)
-- Format:
--   • 10 detailed questions with complete solutions provided as COMMENTED hints.
--   • To run a solution: copy the commented block and remove leading '--'.
-- Guidance:
--   • Anchor variables and records with %TYPE / %ROWTYPE for schema safety.
--   • Guard single-row SELECT INTO with NO_DATA_FOUND / TOO_MANY_ROWS handling.
--   • Prefer BULK COLLECT + LIMIT for large result sets; use RETURNING INTO to avoid extra SELECTs.

SET SERVEROUTPUT ON;

--------------------------------------------------------------------------------
-- Q1 (Single-row SELECT INTO): Print emp_name for emp_id=1.
-- Answer (commented):
-- DECLARE
--   v_name emp_demo.emp_name%TYPE;
-- BEGIN
--   SELECT emp_name INTO v_name FROM emp_demo WHERE emp_id=1;
--   DBMS_OUTPUT.PUT_LINE('name='||v_name);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q2 (NO_DATA_FOUND): Try emp_id=999, catch NO_DATA_FOUND and print a friendly message.
-- Answer (commented):
-- DECLARE
--   v_name emp_demo.emp_name%TYPE;
-- BEGIN
--   BEGIN
--     SELECT emp_name INTO v_name FROM emp_demo WHERE emp_id=999;
--   EXCEPTION WHEN NO_DATA_FOUND THEN
--     DBMS_OUTPUT.PUT_LINE('no row for id=999');
--   END;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q3 (TOO_MANY_ROWS): Insert a duplicate name and then query by name to raise TOO_MANY_ROWS.
-- Answer (commented):
-- BEGIN
--   INSERT INTO emp_demo VALUES (100,'Avi',10,60000,SYSDATE);
--   COMMIT;
--   DECLARE v_id emp_demo.emp_id%TYPE; BEGIN
--     SELECT emp_id INTO v_id FROM emp_demo WHERE emp_name='Avi';
--   EXCEPTION WHEN TOO_MANY_ROWS THEN
--     DBMS_OUTPUT.PUT_LINE('duplicate names detected');
--   END;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q4 (%ROWTYPE): Load full row for emp_id=2 into r emp_demo%ROWTYPE and print id,name,salary.
-- Answer (commented):
-- DECLARE
--   r emp_demo%ROWTYPE;
-- BEGIN
--   SELECT * INTO r FROM emp_demo WHERE emp_id=2;
--   DBMS_OUTPUT.PUT_LINE('id='||r.emp_id||', name='||r.emp_name||', sal='||r.salary);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q5 (JOIN SELECT INTO): For emp_id=3, print 'name works in dept_name' using a JOIN.
-- Answer (commented):
-- DECLARE
--   v_emp  emp_demo.emp_name%TYPE;
--   v_dept dept_demo.dept_name%TYPE;
-- BEGIN
--   SELECT e.emp_name, d.dept_name
--   INTO   v_emp,     v_dept
--   FROM   emp_demo e JOIN dept_demo d ON d.dept_id=e.dept_id
--   WHERE  e.emp_id=3;
--   DBMS_OUTPUT.PUT_LINE(v_emp||' works in '||v_dept);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q6 (Aggregate + NVL): Print average salary for dept 10 and show SQL%%ROWCOUNT.
-- Answer (commented):
-- DECLARE
--   v_avg NUMBER;
-- BEGIN
--   SELECT NVL(AVG(salary),0) INTO v_avg FROM emp_demo WHERE dept_id=10;
--   DBMS_OUTPUT.PUT_LINE('avg='||ROUND(v_avg));
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT); -- for SELECT INTO, this is 1
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q7 (BULK COLLECT + LIMIT): Fetch names in batches of 2 and print.
-- Answer (commented):
-- DECLARE
--   TYPE t_vc IS TABLE OF VARCHAR2(50);
--   t t_vc;
--   lim CONSTANT PLS_INTEGER := 2;
--   off NUMBER := 0;
-- BEGIN
--   LOOP
--     SELECT emp_name BULK COLLECT INTO t
--     FROM emp_demo
--     ORDER BY emp_id
--     OFFSET off ROWS FETCH NEXT lim ROWS ONLY;
--     EXIT WHEN t.COUNT=0;
--     FOR i IN 1..t.COUNT LOOP DBMS_OUTPUT.PUT_LINE('name='||t(i)); END LOOP;
--     off := off + lim;
--   END LOOP;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q8 (Cursor FOR LOOP): List 'emp=..., dept=...' for dept 10 using a cursor loop.
-- Answer (commented):
-- BEGIN
--   FOR r IN (
--     SELECT e.emp_name emp, d.dept_name dept
--     FROM emp_demo e JOIN dept_demo d ON d.dept_id=e.dept_id
--     WHERE e.dept_id=10 ORDER BY e.emp_id
--   ) LOOP
--     DBMS_OUTPUT.PUT_LINE('emp='||r.emp||', dept='||r.dept);
--   END LOOP;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q9 (RETURNING INTO): Increase salary of emp_id=2 by 500 and print new salary and SQL%%ROWCOUNT.
-- Answer (commented):
-- DECLARE
--   v_new emp_demo.salary%TYPE;
-- BEGIN
--   UPDATE emp_demo SET salary=salary+500 WHERE emp_id=2 RETURNING salary INTO v_new;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT||', new='||v_new);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q10 (Parameterized cursor): Declare c_emp(p_dept) and print names for dept_id=10.
-- Answer (commented):
-- DECLARE
--   CURSOR c_emp(p_dept NUMBER) IS
--     SELECT emp_name FROM emp_demo WHERE dept_id=p_dept ORDER BY emp_id;
-- BEGIN
--   FOR r IN c_emp(10) LOOP
--     DBMS_OUTPUT.PUT_LINE('name='||r.emp_name);
--   END LOOP;
-- END;
-- /
--------------------------------------------------------------------------------
-- End of Assignment
--------------------------------------------------------------------------------
