-- Script: assignment_record_modification_operations.sql
-- Session: 032 - Record Modification Operations (Production Patterns)
-- Format:
--   • 10 detailed questions with complete solutions provided as COMMENTED hints.
--   • To run a solution: copy the commented block and remove leading '--'.
-- Guidance:
--   • Use RETURNING INTO to avoid extra SELECTs after UPDATE.
--   • Prefer MERGE for set-based upserts over procedural loops.
--   • Detect lost updates via version/timestamp checks and SQL%%ROWCOUNT.

SET SERVEROUTPUT ON;

--------------------------------------------------------------------------------
-- Q1 (UPDATE + RETURNING): Raise salary for emp_id=1 by 250 and print new salary.
-- Answer (commented):
-- DECLARE
--   v_new emp_mod.salary%TYPE;
-- BEGIN
--   UPDATE emp_mod SET salary = salary + 250, last_updated=SYSDATE WHERE emp_id=1
--   RETURNING salary INTO v_new;
--   DBMS_OUTPUT.PUT_LINE('new='||v_new);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q2 (Optimistic locking): Update emp_id=2 when version matches; bump version by 1; print SQL%%ROWCOUNT.
-- Answer (commented):
-- DECLARE
--   v_exp emp_mod.version_no%TYPE;
-- BEGIN
--   SELECT version_no INTO v_exp FROM emp_mod WHERE emp_id=2;
--   UPDATE emp_mod SET salary=salary+100, version_no=version_no+1, last_updated=SYSDATE
--   WHERE emp_id=2 AND version_no=v_exp;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q3 (Correlated subquery): Set salary to dept average for dept 10 employees.
-- Answer (commented):
-- BEGIN
--   UPDATE emp_mod e
--   SET    salary = (SELECT ROUND(AVG(salary),2) FROM emp_mod WHERE dept_id=10),
--          last_updated = SYSDATE
--   WHERE  e.dept_id=10;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q4 (WHERE CURRENT OF): Use FOR UPDATE cursor on dept 20 and append '-u' to emails.
-- Answer (commented):
-- DECLARE
--   CURSOR c IS SELECT emp_id, email FROM emp_mod WHERE dept_id=20 FOR UPDATE OF email NOWAIT;
-- BEGIN
--   FOR r IN c LOOP
--     UPDATE emp_mod SET email = r.email||'-u', last_updated=SYSDATE WHERE CURRENT OF c;
--   END LOOP;
--   DBMS_OUTPUT.PUT_LINE('done');
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q5 (MERGE upsert): Upsert (emp_id=8,'Isha',dept=10,sal=72000) into emp_mod.
-- Answer (commented):
-- BEGIN
--   MERGE INTO emp_mod t
--   USING (SELECT 8 emp_id, 'Isha' emp_name, 10 dept_id, 72000 salary FROM dual) s
--   ON (t.emp_id=s.emp_id)
--   WHEN MATCHED THEN UPDATE SET t.salary=s.salary, t.last_updated=SYSDATE
--   WHEN NOT MATCHED THEN INSERT (emp_id,emp_name,dept_id,salary,email,version_no,last_updated)
--     VALUES (s.emp_id,s.emp_name,s.dept_id,s.salary,LOWER(s.emp_name)||'@example.com',1,SYSDATE);
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q6 (MERGE conditional): For dept 10 only, raise salary 2% using MERGE; print affected count.
-- Answer (commented):
-- BEGIN
--   MERGE INTO emp_mod t
--   USING (SELECT emp_id, salary FROM emp_mod WHERE dept_id=10) s
--   ON (t.emp_id=s.emp_id)
--   WHEN MATCHED THEN UPDATE SET t.salary=ROUND(s.salary*1.02,2), t.last_updated=SYSDATE;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q7 (Bulk FORALL UPDATE): Update 3 ids with new salaries; SAVE EXCEPTIONS to capture failures.
-- Answer (commented):
-- DECLARE
--   TYPE t_upd IS TABLE OF emp_mod.emp_id%TYPE;
--   ids t_upd := t_upd(1, 2, 999);
--   errors EXCEPTION; PRAGMA EXCEPTION_INIT(errors, -24381);
-- BEGIN
--   BEGIN
--     FORALL i IN 1..ids.COUNT SAVE EXCEPTIONS
--       UPDATE emp_mod SET salary=salary+111, last_updated=SYSDATE WHERE emp_id=ids(i);
--   EXCEPTION WHEN errors THEN
--     DBMS_OUTPUT.PUT_LINE('bulk errors='||SQL%BULK_EXCEPTIONS.COUNT);
--   END;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q8 (SAVEPOINT/ROLLBACK): Perform two updates; rollback second if 0 rows affected; commit the first.
-- Answer (commented):
-- DECLARE
--   bad NUMBER := 999;
-- BEGIN
--   SAVEPOINT s1;
--   UPDATE emp_mod SET salary=salary+50 WHERE emp_id=1;
--   SAVEPOINT s2;
--   UPDATE emp_mod SET salary=salary+50 WHERE emp_id=bad;
--   IF SQL%ROWCOUNT=0 THEN ROLLBACK TO s2; DBMS_OUTPUT.PUT_LINE('rolled back second'); END IF;
--   COMMIT;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q9 (Detect lost update via timestamp): Update only if last_updated < SYSDATE; print rows.
-- Answer (commented):
-- BEGIN
--   UPDATE emp_mod SET salary=salary+10, last_updated=SYSDATE
--   WHERE emp_id=1 AND last_updated < SYSDATE;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q10 (Audit on change): After a raise for id=1, insert into emp_mod_audit with old and new salaries.
-- Answer (commented):
-- DECLARE
--   v_old NUMBER; v_new NUMBER;
-- BEGIN
--   SELECT salary INTO v_old FROM emp_mod WHERE emp_id=1;
--   UPDATE emp_mod SET salary=salary+123, last_updated=SYSDATE WHERE emp_id=1
--   RETURNING salary INTO v_new;
--   INSERT INTO emp_mod_audit(emp_id, action, old_salary, new_salary, note)
--   VALUES (1,'RAISE', v_old, v_new, 'assignment');
--   DBMS_OUTPUT.PUT_LINE('audited');
-- END;
-- /
--------------------------------------------------------------------------------
-- End of Assignment
--------------------------------------------------------------------------------
