SET SERVEROUTPUT ON SIZE UNLIMITED;
--------------------------------------------------------------------------------
-- Session 093 – Statement-Level Execution
-- Purpose:
--   Explore how statement-level triggers work in contrast to row-level triggers.
--   Statement-level triggers fire ONCE per DML statement, regardless of the
--   number of rows affected. They are ideal for:
--     • Logging who performed the DML
--     • Enforcing coarse-grained business rules
--     • Summary/aggregate maintenance
--
-- Assumptions:
--   • Base objects from earlier sessions exist (tg_employees, audit/history tables).
--   • DBMS_OUTPUT is enabled in the client (SET SERVEROUTPUT ON).
--------------------------------------------------------------------------------


/******************************************************************************
 EXAMPLE 1 – AFTER UPDATE (statement-level) logging trigger
  Goal:
    Log that an UPDATE occurred on tg_employees, without per-row details.
******************************************************************************/
CREATE OR REPLACE TRIGGER trg_emp_stmt_after_update_log
AFTER UPDATE ON tg_employees
DECLARE
  v_user  VARCHAR2(30);
  v_time  DATE;
BEGIN
  v_user := USER;
  v_time := SYSDATE;

  DBMS_OUTPUT.PUT_LINE(
    'Statement-level AFTER UPDATE fired by user='||v_user||
    ' at '||TO_CHAR(v_time,'YYYY-MM-DD HH24:MI:SS')
  );
END;
/
--------------------------------------------------------------------------------


/******************************************************************************
 EXAMPLE 2 – BEFORE DELETE (statement-level) guardrail
  Goal:
    Prevent large DELETE operations during business hours at a coarse level.
******************************************************************************/
CREATE OR REPLACE TRIGGER trg_emp_stmt_before_delete_guard
BEFORE DELETE ON tg_employees
DECLARE
  v_hour VARCHAR2(2);
BEGIN
  v_hour := TO_CHAR(SYSDATE,'HH24');

  IF v_hour BETWEEN '09' AND '18' THEN
    RAISE_APPLICATION_ERROR(
      -33001,
      'Bulk DELETE on tg_employees not allowed during business hours (09-18).'
    );
  END IF;
END;
/
--------------------------------------------------------------------------------


/******************************************************************************
 EXAMPLE 3 – AFTER INSERT (statement-level) summary check
  Goal:
    After an INSERT statement completes, report the total row count.
******************************************************************************/
CREATE OR REPLACE TRIGGER trg_emp_stmt_after_insert_summary
AFTER INSERT ON tg_employees
DECLARE
  v_cnt PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM tg_employees;

  DBMS_OUTPUT.PUT_LINE(
    'AFTER INSERT statement-level trigger: total employees now = '||v_cnt
  );
END;
/
--------------------------------------------------------------------------------


/******************************************************************************
 EXAMPLE 4 – BEFORE UPDATE (statement-level) change window enforcement
  Goal:
    Block ANY update on tg_employees outside of a specific maintenance window.
******************************************************************************/
CREATE OR REPLACE TRIGGER trg_emp_stmt_before_update_window
BEFORE UPDATE ON tg_employees
DECLARE
  v_day  VARCHAR2(3);
  v_hour VARCHAR2(2);
BEGIN
  v_day  := TO_CHAR(SYSDATE,'DY');   -- e.g., MON, TUE
  v_hour := TO_CHAR(SYSDATE,'HH24'); -- 00-23

  -- Allow maintenance window on Sunday between 01:00 and 03:00 only
  IF NOT (v_day = 'SUN' AND v_hour BETWEEN '01' AND '03') THEN
    RAISE_APPLICATION_ERROR(
      -33002,
      'Updates allowed only during Sunday 01:00–03:00 maintenance window.'
    );
  END IF;
END;
/
--------------------------------------------------------------------------------


/******************************************************************************
 EXAMPLE 5 – AFTER INSERT OR UPDATE OR DELETE (statement-level) generic audit
  Goal:
    Maintain a coarse-grained audit table that stores which DML operation
    occurred on tg_employees, by which user, and when.
******************************************************************************/
-- Simple generic audit table for statement-level operations
CREATE TABLE stmt_dml_audit (
  audit_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  table_name  VARCHAR2(30),
  operation   VARCHAR2(10),
  executed_by VARCHAR2(30),
  executed_on DATE
);
/

-- AFTER INSERT statement-level on tg_employees
CREATE OR REPLACE TRIGGER trg_emp_stmt_ai
AFTER INSERT ON tg_employees
BEGIN
  INSERT INTO stmt_dml_audit(table_name, operation, executed_by, executed_on)
  VALUES('TG_EMPLOYEES','INSERT',USER,SYSDATE);
END;
/
--------------------------------------------------------------------------------

-- AFTER UPDATE statement-level on tg_employees
CREATE OR REPLACE TRIGGER trg_emp_stmt_au
AFTER UPDATE ON tg_employees
BEGIN
  INSERT INTO stmt_dml_audit(table_name, operation, executed_by, executed_on)
  VALUES('TG_EMPLOYEES','UPDATE',USER,SYSDATE);
END;
/
--------------------------------------------------------------------------------

-- AFTER DELETE statement-level on tg_employees
CREATE OR REPLACE TRIGGER trg_emp_stmt_ad
AFTER DELETE ON tg_employees
BEGIN
  INSERT INTO stmt_dml_audit(table_name, operation, executed_by, executed_on)
  VALUES('TG_EMPLOYEES','DELETE',USER,SYSDATE);
END;
/
--------------------------------------------------------------------------------


/******************************************************************************
 EXAMPLE 6 – Demonstration block: Compare row-level vs statement-level
  Goal:
    Show in comments and output how many times each trigger fires.
******************************************************************************/
BEGIN
  DBMS_OUTPUT.PUT_LINE('Demonstration comment:');
  DBMS_OUTPUT.PUT_LINE('- Row-level triggers fire once per affected row.');
  DBMS_OUTPUT.PUT_LINE('- Statement-level triggers fire once per DML statement.');
  DBMS_OUTPUT.PUT_LINE('Try running: UPDATE tg_employees SET salary = salary + 1000;');
  DBMS_OUTPUT.PUT_LINE('- Row-level: fires for every employee row updated.');
  DBMS_OUTPUT.PUT_LINE('- Statement-level: fires exactly once for the entire UPDATE.');
END;
/
--------------------------------------------------------------------------------

-- End of Lesson – Session 093 Statement-Level Execution
--------------------------------------------------------------------------------
