-- Demo Script: setup_workspace.sql
-- Objective: Prepare Oracle PL/SQL workspace

CREATE USER plsql_lab IDENTIFIED BY oracle123;
GRANT CONNECT, RESOURCE TO plsql_lab;
ALTER USER plsql_lab QUOTA UNLIMITED ON USERS;

CONNECT plsql_lab/oracle123@localhost:1521/xepdb1;
SHOW USER;

CREATE TABLE training_audit (
  session_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  session_name VARCHAR2(100),
  start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO training_audit (session_name) VALUES ('Session 001 - Course Navigation');
COMMIT;
