-- Demo Script: lab_resources_setup.sql
-- Objective: Configure Oracle lab resources and directories

CONNECT sys/oracle@localhost:1521/xepdb1 AS SYSDBA;

-- Step 1: Create directories for external file access
CREATE OR REPLACE DIRECTORY LAB_SCRIPTS AS '/c/EMS/Terraform/oracle-plsql-complete-developer-path/scripts';
CREATE OR REPLACE DIRECTORY LAB_LOGS AS '/c/EMS/Terraform/oracle-plsql-complete-developer-path/logs';
CREATE OR REPLACE DIRECTORY LAB_BACKUPS AS '/c/EMS/Terraform/oracle-plsql-complete-developer-path/backups';

-- Step 2: Grant privileges to training user
GRANT READ, WRITE ON DIRECTORY LAB_SCRIPTS TO training;
GRANT READ, WRITE ON DIRECTORY LAB_LOGS TO training;
GRANT READ, WRITE ON DIRECTORY LAB_BACKUPS TO training;

-- Step 3: Create execution log table
CONNECT training/training123@localhost:1521/xepdb1;

CREATE TABLE lab_execution_log (
  log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  lab_name VARCHAR2(100),
  run_by VARCHAR2(50),
  run_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 4: Insert validation record
INSERT INTO lab_execution_log (lab_name, run_by)
VALUES ('Hands-On Lab Resources Setup', USER);
COMMIT;

SELECT * FROM lab_execution_log;
