-- Script: assignment_data_insertion_techniques.sql
-- Session: 031 - Data Insertion Techniques (Production Patterns)
-- Format:
--   • 10 detailed questions with complete solutions provided as COMMENTED hints.
--   • To run a solution: copy the commented block and remove leading '--'.
-- Guidance:
--   • Use RETURNING INTO to avoid extra SELECTs after INSERT.
--   • Prefer set-based INSERT...SELECT for bulk derivations.
--   • For conditional fan-out, use INSERT ALL / INSERT FIRST.
--   • For array DML, combine FORALL with SAVE EXCEPTIONS to isolate failures.

SET SERVEROUTPUT ON;

--------------------------------------------------------------------------------
-- Q1 (Single-row + RETURNING): Insert id=101, name='Arun', dept=10; RETURNING created_on into var.
-- Answer (commented):
-- DECLARE
--   v_created emp_ins.created_on%TYPE;
-- BEGIN
--   INSERT INTO emp_ins(emp_id, emp_name, dept_id, email)
--   VALUES (101,'Arun',10,'arun@example.com')
--   RETURNING created_on INTO v_created;
--   DBMS_OUTPUT.PUT_LINE('created_on='||TO_CHAR(v_created,'YYYY-MM-DD'));
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q2 (DEFAULT VALUES): Insert id=102 with only mandatory fields; verify salary defaulted.
-- Answer (commented):
-- BEGIN
--   INSERT INTO emp_ins(emp_id, emp_name, dept_id) VALUES (102,'Bela',10);
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q3 (INSERT...SELECT): Insert one row per dept using emp_ins_seq for emp_id and 'Seed-'||dept_id for name.
-- Answer (commented):
-- BEGIN
--   INSERT INTO emp_ins(emp_id, emp_name, dept_id)
--   SELECT emp_ins_seq.NEXTVAL, 'Seed-'||dept_id, dept_id FROM dept_ins;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q4 (INSERT ALL): From DUAL, insert into emp_ins (id=103) and emp_audit record with action='INSERT'.
-- Answer (commented):
-- DECLARE
--   v_id NUMBER := 103;
-- BEGIN
--   INSERT ALL
--     INTO emp_ins(emp_id, emp_name, dept_id, email) VALUES (v_id,'Chirag',10,'chirag@example.com')
--     INTO emp_audit(audit_id, emp_id, action, note)  VALUES (emp_ins_seq.NEXTVAL, v_id, 'INSERT', 'batch route')
--   SELECT 1 FROM dual;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q5 (INSERT FIRST): Route to audit note 'FIN' when dept=20 else 'ENG' when dept=10.
-- Answer (commented):
-- DECLARE
--   v_id NUMBER := 104; v_dept NUMBER := 20;
-- BEGIN
--   INSERT FIRST
--     WHEN v_dept = 20 THEN
--       INTO emp_audit(audit_id, emp_id, action, note) VALUES (emp_ins_seq.NEXTVAL, v_id, 'INSERT', 'FIN')
--     WHEN v_dept = 10 THEN
--       INTO emp_audit(audit_id, emp_id, action, note) VALUES (emp_ins_seq.NEXTVAL, v_id, 'INSERT', 'ENG')
--   SELECT 1 FROM dual;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q6 (Sequence): Use emp_ins_seq.NEXTVAL to insert id + RETURNING email.
-- Answer (commented):
-- DECLARE
--   v_id NUMBER := emp_ins_seq.NEXTVAL; v_mail emp_ins.email%TYPE;
-- BEGIN
--   INSERT INTO emp_ins(emp_id, emp_name, dept_id, email)
--   VALUES (v_id,'Dia',10,'dia@example.com') RETURNING email INTO v_mail;
--   DBMS_OUTPUT.PUT_LINE('id='||v_id||' email='||v_mail);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q7 (Validation): Check dept exists before INSERT; if not, print 'Abort' and do not insert.
-- Answer (commented):
-- DECLARE
--   v_dept NUMBER := 99; v_cnt PLS_INTEGER;
-- BEGIN
--   SELECT COUNT(*) INTO v_cnt FROM dept_ins WHERE dept_id=v_dept;
--   IF v_cnt=0 THEN DBMS_OUTPUT.PUT_LINE('Abort: bad dept'); RETURN; END IF;
--   INSERT INTO emp_ins(emp_id, emp_name, dept_id) VALUES (105,'Eka',v_dept);
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q8 (Handle duplicate): Attempt duplicate emp_id insert and handle DUP_VAL_ON_INDEX.
-- Answer (commented):
-- BEGIN
--   BEGIN
--     INSERT INTO emp_ins(emp_id, emp_name, dept_id) VALUES (2,'Dup',10);
--   EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
--     DBMS_OUTPUT.PUT_LINE('Handled duplicate id=2');
--   END;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q9 (Bulk FORALL + SAVE EXCEPTIONS): Insert 3 rows, with one duplicate to show error capture.
-- Answer (commented):
-- DECLARE
--   TYPE t_emp IS TABLE OF emp_ins%ROWTYPE;
--   v t_emp := t_emp();
--   errors EXCEPTION; PRAGMA EXCEPTION_INIT(errors, -24381);
-- BEGIN
--   v.EXTEND(3);
--   v(1).emp_id := 106; v(1).emp_name:='Farah'; v(1).dept_id:=10; v(1).email:='farah@example.com';
--   v(2).emp_id := 2;   v(2).emp_name:='Dup';   v(2).dept_id:=10; v(2).email:='dup@example.com';
--   v(3).emp_id := 107; v(3).emp_name:='Gautam';v(3).dept_id:=20; v(3).email:='gautam@example.com';
--   BEGIN
--     FORALL i IN 1..v.COUNT SAVE EXCEPTIONS
--       INSERT INTO emp_ins(emp_id,emp_name,dept_id,email)
--       VALUES (v(i).emp_id, v(i).emp_name, v(i).dept_id, v(i).email);
--   EXCEPTION WHEN errors THEN
--     DBMS_OUTPUT.PUT_LINE('bulk errors='||SQL%BULK_EXCEPTIONS.COUNT);
--   END;
-- END;
-- /
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Q10 (INSERT...SELECT transformation): Insert rows for ENG dept with name prefix 'ENG-'; show count.
-- Answer (commented):
-- BEGIN
--   INSERT INTO emp_ins(emp_id, emp_name, dept_id, email)
--   SELECT emp_ins_seq.NEXTVAL, 'ENG-'||emp_name, dept_id, email FROM emp_ins WHERE dept_id=10;
--   DBMS_OUTPUT.PUT_LINE('rows='||SQL%ROWCOUNT);
-- END;
-- /
--------------------------------------------------------------------------------
-- End of Assignment
--------------------------------------------------------------------------------
